#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          # 开启动态路由
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: route-user
#          uri: lb://user-service
#          predicates:
#            - Path=/api/v1/users/**
#          filters:
#            - StripPrefix=2
#        - id: route-content
#          uri: lb://content-service
#          predicates:
#            - Path=/api/v1/shares/**
#            - ShareId=1,10
#          filters:
#            - StripPrefix=2
#        - id: route-notice
#          uri: lb://notice-service
#          predicates:
#            - Path=/api/v1/notices/**
#            - After=2022-11-22T09:13:44.000+00:00[Asia/Shanghai]
#            - Cookie=hello, world
#          filters:
#            - StripPrefix=2
