server:
  port: 8081

#spring:
#  application:
#    name: user-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        heart-beat-interval: 5000
#        heart-beat-timeout: 20000
#        namespace: dev
#        register-enabled: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/share?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      pool-name: TestHikari
#      connection-timeout: 5000
#      idle-timeout: 30000
#      maximum-pool-size: 10
#      minimum-idle: 5
#      max-lifetime: 60000
#      auto-commit: true
#  jpa:
#    open-in-view: false
