server:
  port: 8081

rocketmq:
  name-server: 121.40.142.78:9876

spring:
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type:
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
      rate: 1000
