server:
  port: 8152
spring:
  application:
    name: cloud-shopcart-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      password: nacos
      username: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/test_distribution_cart_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: TestHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true

seata:
  application-id: cloud-shopcart-service
#  enabled: true
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      namespace: seata
      group: DEFAULT_GROUP
      cluster: default
      username: nacos
      password: nacos
  tx-service-group: seata-server-group
  service:
    vgroup-mapping:
      seata-server-group: default