server:
  port: 8082

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      # 全局超时配置
      default:
        # 网络连接阶段1秒超时
        connectTimeout: 1000
        # 服务请求响应阶段5秒超时
        readTimeout: 5000

rocketmq:
  name-server: 121.40.142.78:9876
  producer:
    group: test-group

spring:
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
      rate: 1000



